function names = batchColumnNames()
names = {'Enabled', 'Name', 'AxiconMode', 'ConeAngleDeg', ...
    'RadialPeriodMm', 'RadialPeriodPx', 'RadialCycles', 'AxiconIndex', ...
    'PhysicalBaseAngleDeg', 'VortexCharge', 'HelicalGamma', ...
    'HelicalOrder', 'HelicalOffsetDeg', 'OmegaInner', 'OmegaOuter', ...
    'GlobalLensFocalMm', 'GlobalXShift2Pi', 'GlobalYShift2Pi', ...
    'GlobalApertureRadiusPx', 'GlobalApertureCenterXpx', ...
    'GlobalApertureCenterYpx', 'SlmSettleSeconds', 'Notes'};
end
