function items = batchSweepParameterItems()
items = {'None', 'ConeAngleDeg', 'RadialPeriodMm', 'RadialPeriodPx', 'RadialCycles', ...
    'VortexCharge', 'HelicalGamma', 'HelicalOrder', 'HelicalOffsetDeg', ...
    'OmegaInner', 'OmegaOuter', 'GlobalLensFocalMm', 'GlobalXShift2Pi', ...
    'GlobalYShift2Pi', 'GlobalApertureRadiusPx', 'GlobalApertureCenterXpx', ...
    'GlobalApertureCenterYpx'};
end
