function job = emptyBatchJob()
job = struct( ...
    'tableIndex', NaN, ...
    'batchIndex', NaN, ...
    'enabled', false, ...
    'name', '', ...
    'options', struct(), ...
    'globalAdjustments', struct(), ...
    'slmSettleSeconds', 0, ...
    'notes', "");
end
