function rows = initialBatchManifestRows(preflight)
rows = repmat(batchManifestRow(), 1, numel(preflight.jobs));
for index = 1:numel(preflight.jobs)
    job = preflight.jobs(index);
    rows(index).BatchIndex = job.batchIndex;
    rows(index).TableIndex = job.tableIndex;
    rows(index).Name = string(job.name);
    rows(index).Status = "pending";
    rows(index).TotalCount = preflight.framesPerJob;
end
end

function row = batchManifestRow()
row = struct( ...
    'BatchIndex', NaN, ...
    'TableIndex', NaN, ...
    'Name', "", ...
    'Status', "", ...
    'StartedAt', "", ...
    'FinishedAt', "", ...
    'OutputFolder', "", ...
    'StackFile', "", ...
    'MetadataFile', "", ...
    'Exposure_us', NaN, ...
    'AutoExposureEnabled', false, ...
    'AutoExposureScoutCount', 0, ...
    'AutoExposureScoutFile', "", ...
    'CapturedCount', 0, ...
    'TotalCount', 0, ...
    'Error', "");
end
