function services = defaultServices(overrides)
%DEFAULTSERVICES Production side-effect boundaries used by app controllers.

if nargin < 1
    overrides = struct();
end

services.stage = struct( ...
    'connect', @lw_connect_stages, ...
    'disconnectAll', @lw_disconnect_all, ...
    'home', @lw_home_stages, ...
    'getPosition', @lw_get_position, ...
    'moveAbsolute', @lw_move_absolute, ...
    'stop', @lw_stop_motion, ...
    'setPulseTrigger', @lw_set_stage_pulse_trigger);
services.daq = struct( ...
    'connect', @lw_connect_daq, ...
    'write', @(daq, value) write(daq, value));
services.laser = struct( ...
    'setPower', @lw_set_laser_power, ...
    'manualExposure', @lw_manual_exposure);
services.carbide = struct( ...
    'baseUrl', @lw_carbide_base_url, ...
    'getBasic', @lw_carbide_get_basic, ...
    'getPresets', @lw_carbide_get_presets, ...
    'setPpDivider', @lw_carbide_set_pp_divider, ...
    'enableOutput', @lw_carbide_enable_output, ...
    'closeOutput', @lw_carbide_close_output, ...
    'selectPreset', @lw_carbide_select_preset, ...
    'applySelectedPreset', @lw_carbide_apply_selected_preset, ...
    'standby', @lw_carbide_standby);
services.flir = struct( ...
    'refreshDevices', @lw_flir_refresh_devices, ...
    'connect', @lw_flir_connect, ...
    'disconnect', @lw_flir_disconnect, ...
    'setExposure', @lw_flir_set_exposure, ...
    'setGain', @lw_flir_set_gain, ...
    'capture', @lw_flir_capture, ...
    'readFloatNode', @lw_flir_read_float_node, ...
    'setCaptureRegion', @lw_flir_set_capture_region, ...
    'startAcquisition', @lw_flir_start_acquisition, ...
    'stopAcquisition', @lw_flir_stop_acquisition, ...
    'grabFrame', @lw_flir_grab_frame, ...
    'isConnected', @lw_flir_is_connected);
services.slm = struct( ...
    'openControl', @lw_slm_control_app, ...
    'batchAction', @lw_batch_action_impl);
services.mako = struct( ...
    'create', @mako_camera_control_app, ...
    'disconnect', @(controller) feval(controller.disconnect), ...
    'shutdown', @(controller) feval(controller.shutdown), ...
    'isConnected', @(controller) logical(feval(controller.isConnected)));
services.execution = struct( ...
    'runPoint', @lw_run_point_mode, ...
    'runStream', @lw_run_stream_mode, ...
    'runCutPlan', @lw_run_cut_plan_mode, ...
    'runZSweep', @lw_run_z_sweep_mode);
services.timer = struct( ...
    'create', @(varargin) timer(varargin{:}));
services.clock = struct( ...
    'pause', @pause, ...
    'tic', @tic, ...
    'toc', @toc);
services.dialog = struct( ...
    'alert', @uialert, ...
    'confirm', @uiconfirm, ...
    'openFile', @uigetfile, ...
    'saveFile', @uiputfile, ...
    'chooseFolder', @uigetdir);
services.ui = struct('drawnow', @(varargin) drawnow(varargin{:}));

services = mergeOverrides(services, overrides);
end

function target = mergeOverrides(target, overrides)
names = fieldnames(overrides);
for index = 1:numel(names)
    name = names{index};
    override = overrides.(name);
    if isfield(target, name) && isstruct(target.(name)) && isstruct(override) && ...
            isscalar(target.(name)) && isscalar(override)
        target.(name) = mergeOverrides(target.(name), override);
    else
        target.(name) = override;
    end
end
end
