function services = validateServices(services)
%VALIDATESERVICES Validate the injectable production side-effect boundary.

arguments
    services (1, 1) struct
end

contracts = { ...
    'stage', ["connect", "disconnectAll", "home", "getPosition", "moveAbsolute", "stop", "setPulseTrigger"]; ...
    'daq', ["connect", "write"]; ...
    'laser', ["setPower", "manualExposure"]; ...
    'carbide', ["baseUrl", "getBasic", "getPresets", "setPpDivider", "enableOutput", ...
        "closeOutput", "selectPreset", "applySelectedPreset", "standby"]; ...
    'flir', ["refreshDevices", "connect", "disconnect", "setExposure", "setGain", "capture", ...
        "readFloatNode", "setCaptureRegion", "startAcquisition", "stopAcquisition", "grabFrame", "isConnected"]; ...
    'slm', ["openControl", "batchAction"]; ...
    'mako', ["create", "disconnect", "shutdown", "isConnected"]; ...
    'execution', ["runPoint", "runStream", "runCutPlan", "runZSweep"]; ...
    'timer', "create"; ...
    'clock', ["pause", "tic", "toc"]; ...
    'dialog', ["alert", "confirm", "openFile", "saveFile", "chooseFolder"]; ...
    'ui', "drawnow"};

services = lw.app.validatePorts("services", services, string(contracts(:, 1)).');
for contractIndex = 1:size(contracts, 1)
    categoryName = string(contracts{contractIndex, 1});
    requiredNames = string(contracts{contractIndex, 2});
    category = services.(categoryName);
    if ~isstruct(category) || ~isscalar(category)
        error('lw:app:InvalidService', 'Service category %s must be a scalar struct.', categoryName);
    end
    category = lw.app.validatePorts("services." + categoryName, category, requiredNames);
    for name = requiredNames
        if ~isa(category.(name), 'function_handle')
            error('lw:app:InvalidService', 'Service %s.%s must be a function handle.', ...
                categoryName, name);
        end
    end
end
end
