function runUi = lw_build_run_tab(tab, callbacks, helpers, options)
%LW_BUILD_RUN_TAB Build run mode, parameters, status, and controls.

runUi = struct();

grid = uigridlayout(tab, [3, 3], ...
    'ColumnWidth', {'0.9x', 6, '1.1x'}, ...
    'RowHeight', {'1x', 6, '0.9x'}, ...
    'Padding', [12, 12, 12, 12], ...
    'RowSpacing', 3, ...
    'ColumnSpacing', 3);
helpers.createGridSplitter(grid, 1, 2, 'column', 1, 3);
helpers.createGridSplitter(grid, 3, 2, 'column', 1, 3);
helpers.createGridSplitter(grid, 2, [1 3], 'row', 1, 3);

modePanel = uipanel(grid, 'Title', 'Run Mode');
modePanel.Layout.Row = 1;
modePanel.Layout.Column = 1;
modeGrid = uigridlayout(modePanel, [2, 1], ...
    'RowHeight', {'fit', '1x'}, ...
    'Padding', [12, 12, 12, 12]);
helpers.enableScrolling(modeGrid);
runUi.RunModeGroup = uibuttongroup(modeGrid, 'Title', 'Execution', ...
    'SelectionChangedFcn', callbacks.runModeChanged);
runUi.RunModeGroup.Layout.Row = 1;
runUi.PointModeRadio = uiradiobutton(runUi.RunModeGroup, 'Text', 'Point Mode', ...
    'Value', true, 'Position', [14, 26, 100, 22]);
runUi.StreamModeRadio = uiradiobutton(runUi.RunModeGroup, 'Text', 'Stream Mode', ...
    'Position', [140, 26, 110, 22]);
runUi.ZSweepModeRadio = uiradiobutton(runUi.RunModeGroup, 'Text', 'Z Sweep Mode', ...
    'Position', [270, 26, 130, 22]);
runUi.CutPlanModeRadio = uiradiobutton(runUi.RunModeGroup, 'Text', 'Cut Plan Mode', ...
    'Position', [14, 2, 130, 22]);
runUi.RunModeHintLabel = uilabel(modeGrid, ...
    'Text', 'Cut Plan Mode runs writing-plan cut rows with laser-off lead-in/out and laser-on edge streams. Z Sweep Mode runs direct repeated Z moves without a loaded plan.');

paramPanel = uipanel(grid, 'Title', 'Run Parameters');
paramPanel.Layout.Row = 1;
paramPanel.Layout.Column = 3;
paramGrid = uigridlayout(paramPanel, [17, 4], ...
    'ColumnWidth', {120, '1x', 120, '1x'}, ...
    'Padding', [12, 12, 12, 12], ...
    'RowSpacing', 6);
helpers.enableScrolling(paramGrid);
runUi.RunParameterGrid = paramGrid;
runUi.PointExposureLabel = helpers.createRightLabel(paramGrid, 'Point Exp (us)', 1, 1);
runUi.PointExposureField = uieditfield(paramGrid, 'numeric');
runUi.PointExposureField.Layout.Row = 1; runUi.PointExposureField.Layout.Column = 2;
runUi.PointPauseLabel = helpers.createRightLabel(paramGrid, 'Point Pause (s)', 1, 3);
runUi.PointPauseField = uieditfield(paramGrid, 'numeric');
runUi.PointPauseField.Layout.Row = 1; runUi.PointPauseField.Layout.Column = 4;
runUi.StreamSpeedLabel = helpers.createRightLabel(paramGrid, 'Stream Speed (mm/s)', 2, 1);
runUi.StreamSpeedField = uieditfield(paramGrid, 'numeric');
runUi.StreamSpeedField.Layout.Row = 2; runUi.StreamSpeedField.Layout.Column = 2;
runUi.ZSweepPowerLabel = helpers.createRightLabel(paramGrid, 'Sweep Power (%)', 2, 3);
runUi.ZSweepPowerField = uieditfield(paramGrid, 'numeric', ...
    'Limits', [0 100], ...
    'ValueChangedFcn', callbacks.zSweepPreviewChanged);
runUi.ZSweepPowerField.Layout.Row = 2; runUi.ZSweepPowerField.Layout.Column = 4;
runUi.TTLGateWidthLabel = helpers.createRightLabel(paramGrid, 'TTL Gate Width (us)', 3, 1);
runUi.TTLGateWidthField = uieditfield(paramGrid, 'numeric');
runUi.TTLGateWidthField.Layout.Row = 3; runUi.TTLGateWidthField.Layout.Column = 2;
runUi.ZSweepDirectionLabel = helpers.createRightLabel(paramGrid, 'Exposure Dir', 3, 3);
runUi.ZSweepDirectionDropDown = uidropdown(paramGrid, ...
    'Items', {'Back -> Front', 'Front -> Back', 'Both Directions'}, ...
    'Value', 'Back -> Front', ...
    'ValueChangedFcn', callbacks.zSweepPreviewChanged);
runUi.ZSweepDirectionDropDown.Layout.Row = 3; runUi.ZSweepDirectionDropDown.Layout.Column = 4;
runUi.ZSweepXLabel = helpers.createRightLabel(paramGrid, 'Sweep X', 4, 1);
runUi.ZSweepXField = uieditfield(paramGrid, 'numeric', ...
    'ValueChangedFcn', callbacks.zSweepPreviewChanged);
runUi.ZSweepXField.Layout.Row = 4; runUi.ZSweepXField.Layout.Column = 2;
runUi.ZSweepYLabel = helpers.createRightLabel(paramGrid, 'Sweep Y', 4, 3);
runUi.ZSweepYField = uieditfield(paramGrid, 'numeric', ...
    'ValueChangedFcn', callbacks.zSweepPreviewChanged);
runUi.ZSweepYField.Layout.Row = 4; runUi.ZSweepYField.Layout.Column = 4;
runUi.ZSweepBackLabel = helpers.createRightLabel(paramGrid, 'Z Back', 5, 1);
runUi.ZSweepBackField = uieditfield(paramGrid, 'numeric', ...
    'ValueChangedFcn', callbacks.zSweepPreviewChanged);
runUi.ZSweepBackField.Layout.Row = 5; runUi.ZSweepBackField.Layout.Column = 2;
runUi.ZSweepFrontLabel = helpers.createRightLabel(paramGrid, 'Z Front', 5, 3);
runUi.ZSweepFrontField = uieditfield(paramGrid, 'numeric', ...
    'ValueChangedFcn', callbacks.zSweepPreviewChanged);
runUi.ZSweepFrontField.Layout.Row = 5; runUi.ZSweepFrontField.Layout.Column = 4;
runUi.ZSweepSpeedLabel = helpers.createRightLabel(paramGrid, 'Sweep Speed (mm/s)', 6, 1);
runUi.ZSweepSpeedField = uieditfield(paramGrid, 'numeric', ...
    'ValueChangedFcn', callbacks.zSweepPreviewChanged);
runUi.ZSweepSpeedField.Layout.Row = 6; runUi.ZSweepSpeedField.Layout.Column = 2;
runUi.ZSweepReturnSpeedLabel = helpers.createRightLabel(paramGrid, 'Return Speed (mm/s)', 6, 3);
runUi.ZSweepReturnSpeedField = uieditfield(paramGrid, 'numeric', ...
    'ValueChangedFcn', callbacks.zSweepPreviewChanged);
runUi.ZSweepReturnSpeedField.Layout.Row = 6; runUi.ZSweepReturnSpeedField.Layout.Column = 4;
runUi.ZSweepRepeatLabel = helpers.createRightLabel(paramGrid, 'Repeat Count', 7, 1);
runUi.ZSweepRepeatField = uieditfield(paramGrid, 'numeric', ...
    'ValueChangedFcn', callbacks.zSweepPreviewChanged);
runUi.ZSweepRepeatField.Layout.Row = 7; runUi.ZSweepRepeatField.Layout.Column = 2;
runUi.ZSweepUseCurrentButton = uibutton(paramGrid, 'Text', 'Use Current Position', ...
    'ButtonPushedFcn', callbacks.useCurrentZSweepPosition);
runUi.ZSweepUseCurrentButton.Layout.Row = 7;
runUi.ZSweepUseCurrentButton.Layout.Column = [3 4];
runUi.ZSweepMatrixCheckBox = uicheckbox(paramGrid, ...
    'Text', 'Parameter Matrix', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepMatrixCheckBox.Layout.Row = 8;
runUi.ZSweepMatrixCheckBox.Layout.Column = [1 2];
runUi.ZSweepMatrixHintLabel = uilabel(paramGrid, ...
    'Text', 'Choose two parameters for X/Y grid axes');
runUi.ZSweepMatrixHintLabel.Layout.Row = 8;
runUi.ZSweepMatrixHintLabel.Layout.Column = [3 4];
runUi.ZSweepMatrixXParamLabel = helpers.createRightLabel(paramGrid, 'X Param', 9, 1);
runUi.ZSweepMatrixXParamDropDown = uidropdown(paramGrid, ...
    'Items', options.zSweepMatrixParameterItems, ...
    'Value', 'Power (%)', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepMatrixXParamDropDown.Layout.Row = 9; runUi.ZSweepMatrixXParamDropDown.Layout.Column = 2;
runUi.ZSweepMatrixYParamLabel = helpers.createRightLabel(paramGrid, 'Y Param', 9, 3);
runUi.ZSweepMatrixYParamDropDown = uidropdown(paramGrid, ...
    'Items', options.zSweepMatrixParameterItems, ...
    'Value', 'Sweep Speed (mm/s)', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepMatrixYParamDropDown.Layout.Row = 9; runUi.ZSweepMatrixYParamDropDown.Layout.Column = 4;
runUi.ZSweepMatrixXValuesLabel = helpers.createRightLabel(paramGrid, 'X Values', 10, 1);
runUi.ZSweepMatrixXValuesField = uieditfield(paramGrid, 'text', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepMatrixXValuesField.Layout.Row = 10; runUi.ZSweepMatrixXValuesField.Layout.Column = 2;
runUi.ZSweepMatrixYValuesLabel = helpers.createRightLabel(paramGrid, 'Y Values', 10, 3);
runUi.ZSweepMatrixYValuesField = uieditfield(paramGrid, 'text', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepMatrixYValuesField.Layout.Row = 10; runUi.ZSweepMatrixYValuesField.Layout.Column = 4;
runUi.ZSweepPitchXLabel = helpers.createRightLabel(paramGrid, 'Pitch X (mm)', 11, 1);
runUi.ZSweepPitchXField = uieditfield(paramGrid, 'numeric', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepPitchXField.Layout.Row = 11; runUi.ZSweepPitchXField.Layout.Column = 2;
runUi.ZSweepPitchYLabel = helpers.createRightLabel(paramGrid, 'Pitch Y (mm)', 11, 3);
runUi.ZSweepPitchYField = uieditfield(paramGrid, 'numeric', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepPitchYField.Layout.Row = 11; runUi.ZSweepPitchYField.Layout.Column = 4;
runUi.ZSweepBlockCheckBox = uicheckbox(paramGrid, ...
    'Text', 'Blocks', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepBlockCheckBox.Layout.Row = 12;
runUi.ZSweepBlockCheckBox.Layout.Column = [1 2];
runUi.ZSweepBlockHintLabel = uilabel(paramGrid, ...
    'Text', 'Blocks form an outer X/Y matrix; each block contains the full matrix above');
runUi.ZSweepBlockHintLabel.Layout.Row = 12;
runUi.ZSweepBlockHintLabel.Layout.Column = [3 4];
runUi.ZSweepBlockParam1Label = helpers.createRightLabel(paramGrid, 'Block X Param', 13, 1);
runUi.ZSweepBlockParam1DropDown = uidropdown(paramGrid, ...
    'Items', options.zSweepMatrixBlockParameterItems, ...
    'Value', 'None', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepBlockParam1DropDown.Layout.Row = 13; runUi.ZSweepBlockParam1DropDown.Layout.Column = 2;
runUi.ZSweepBlockValues1Label = helpers.createRightLabel(paramGrid, 'Block X Values', 13, 3);
runUi.ZSweepBlockValues1Field = uieditfield(paramGrid, 'text', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepBlockValues1Field.Layout.Row = 13; runUi.ZSweepBlockValues1Field.Layout.Column = 4;
runUi.ZSweepBlockParam2Label = helpers.createRightLabel(paramGrid, 'Block Y Param', 14, 1);
runUi.ZSweepBlockParam2DropDown = uidropdown(paramGrid, ...
    'Items', options.zSweepMatrixBlockParameterItems, ...
    'Value', 'None', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepBlockParam2DropDown.Layout.Row = 14; runUi.ZSweepBlockParam2DropDown.Layout.Column = 2;
runUi.ZSweepBlockValues2Label = helpers.createRightLabel(paramGrid, 'Block Y Values', 14, 3);
runUi.ZSweepBlockValues2Field = uieditfield(paramGrid, 'text', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepBlockValues2Field.Layout.Row = 14; runUi.ZSweepBlockValues2Field.Layout.Column = 4;
runUi.ZSweepBlockPitchXLabel = helpers.createRightLabel(paramGrid, 'Block Pitch X (mm)', 15, 1);
runUi.ZSweepBlockPitchXField = uieditfield(paramGrid, 'numeric', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepBlockPitchXField.Layout.Row = 15; runUi.ZSweepBlockPitchXField.Layout.Column = 2;
runUi.ZSweepBlockPitchYLabel = helpers.createRightLabel(paramGrid, 'Block Pitch Y (mm)', 15, 3);
runUi.ZSweepBlockPitchYField = uieditfield(paramGrid, 'numeric', ...
    'ValueChangedFcn', callbacks.zSweepMatrixChanged);
runUi.ZSweepBlockPitchYField.Layout.Row = 15; runUi.ZSweepBlockPitchYField.Layout.Column = 4;
runUi.AutoStandbyAfterRunCheckBox = uicheckbox(paramGrid, ...
    'Text', 'Auto standby after run');
runUi.AutoStandbyAfterRunCheckBox.Layout.Row = 16;
runUi.AutoStandbyAfterRunCheckBox.Layout.Column = [1 4];
runUi.AutoStandbyAfterRunCheckBox.Tooltip = 'Send Carbide to standby after a run finishes normally';
runUi.RunParameterHintLabel = uilabel(paramGrid, ...
    'Text', 'Loaded plans carry their own execution power. Sweep Power is used only by Z Sweep Mode.');
runUi.RunParameterHintLabel.Layout.Row = 17;
runUi.RunParameterHintLabel.Layout.Column = [1 4];

statusPanel = uipanel(grid, 'Title', 'Execution Status');
statusPanel.Layout.Row = 3;
statusPanel.Layout.Column = 1;
statusGrid = uigridlayout(statusPanel, [4, 2], ...
    'ColumnWidth', {120, '1x'}, ...
    'Padding', [12, 12, 12, 12], ...
    'RowSpacing', 8);
helpers.enableScrolling(statusGrid);
helpers.createRightLabel(statusGrid, 'Source', 1, 1);
runUi.RunSourceField = uieditfield(statusGrid, 'text', 'Editable', 'off');
runUi.RunSourceField.Layout.Row = 1; runUi.RunSourceField.Layout.Column = 2;
helpers.createRightLabel(statusGrid, 'Supported', 2, 1);
runUi.RunSupportedField = uieditfield(statusGrid, 'text', 'Editable', 'off');
runUi.RunSupportedField.Layout.Row = 2; runUi.RunSupportedField.Layout.Column = 2;
helpers.createRightLabel(statusGrid, 'Progress', 3, 1);
runUi.RunProgressField = uieditfield(statusGrid, 'text', 'Editable', 'off');
runUi.RunProgressField.Layout.Row = 3; runUi.RunProgressField.Layout.Column = 2;
helpers.createRightLabel(statusGrid, 'Current', 4, 1);
runUi.RunCurrentField = uieditfield(statusGrid, 'text', 'Editable', 'off');
runUi.RunCurrentField.Layout.Row = 4; runUi.RunCurrentField.Layout.Column = 2;

controlPanel = uipanel(grid, 'Title', 'Controls');
controlPanel.Layout.Row = 3;
controlPanel.Layout.Column = 3;
controlGrid = uigridlayout(controlPanel, [6, 1], ...
    'RowHeight', {'fit', 'fit', 'fit', 'fit', 'fit', '1x'}, ...
    'Padding', [12, 12, 12, 12], ...
    'RowSpacing', 12);
helpers.enableScrolling(controlGrid);
runUi.GoToFirstPointButton = uibutton(controlGrid, 'Text', 'Go to First Point', ...
    'ButtonPushedFcn', callbacks.goToFirstPoint);
runUi.CheckBoundsButton = uibutton(controlGrid, 'Text', 'Check Bounds', ...
    'ButtonPushedFcn', callbacks.checkBounds);
runUi.StartRunButton = uibutton(controlGrid, 'Text', 'Start Run', ...
    'ButtonPushedFcn', callbacks.startRun);
runUi.PauseResumeButton = uibutton(controlGrid, 'Text', 'Pause', ...
    'ButtonPushedFcn', callbacks.pauseResumeRun);
runUi.StopRunButton = uibutton(controlGrid, 'Text', 'STOP', ...
    'BackgroundColor', [0.95, 0.25, 0.25], ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', callbacks.stopRequested);
uilabel(controlGrid, 'Text', 'Pause waits for a safe boundary; STOP requests a safe shutdown.');
end
