function slmUi = lw_build_slm_tab(tab, callbacks)
%LW_BUILD_SLM_TAB Build the SLM tab and return its UI handles.

slmUi = struct();

grid = uigridlayout(tab, [2, 1], ...
    'RowHeight', {'fit', '1x'}, ...
    'Padding', [12, 12, 12, 12], ...
    'RowSpacing', 8);
slmUi.OpenSlmControlButton = uibutton(grid, ...
    'Text', 'Open SLM Control', ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', callbacks.openSlmControl);
slmUi.OpenSlmControlButton.Layout.Row = 1;
slmUi.OpenSlmControlButton.Layout.Column = 1;
end
