function logUi = lw_build_log_area(parent, callbacks, helpers)
%LW_BUILD_LOG_AREA Build the app log panel and return its UI handles.

logUi = struct();

logPanel = uipanel(parent, 'Title', 'Log / Messages');
logPanel.Layout.Row = 3;

logGrid = uigridlayout(logPanel, [1, 2], ...
    'ColumnWidth', {'1x', 96}, ...
    'Padding', [8, 8, 8, 8], ...
    'ColumnSpacing', 8);
logUi.LogTextArea = uitextarea(logGrid, ...
    'Editable', 'off', ...
    'WordWrap', 'off', ...
    'Value', {'[--:--:--] Starting app...'});
logUi.LogTextArea.Layout.Row = 1;
logUi.LogTextArea.Layout.Column = 1;

logButtonGrid = uigridlayout(logGrid, [2, 1], ...
    'RowHeight', {'fit', 'fit'}, ...
    'Padding', [0, 0, 0, 0], ...
    'RowSpacing', 8);
helpers.enableScrolling(logButtonGrid);
logButtonGrid.Layout.Row = 1;
logButtonGrid.Layout.Column = 2;

logUi.ClearLogButton = uibutton(logButtonGrid, 'Text', 'Clear Log', ...
    'ButtonPushedFcn', callbacks.clearLog);
logUi.ClearLogButton.Tooltip = 'Clear the log window';

logUi.ExportLogButton = uibutton(logButtonGrid, 'Text', 'Export Log', ...
    'ButtonPushedFcn', callbacks.exportLog);
logUi.ExportLogButton.Tooltip = 'Export the current log to a text file';
end
