function runUi = lw_build_run_tab(tab, callbacks, helpers)
%LW_BUILD_RUN_TAB Build plan-driven execution status and lifecycle controls.

runUi = struct();

grid = uigridlayout(tab, [1, 3], ...
    'ColumnWidth', {'1.25x', 6, '0.75x'}, ...
    'Padding', [12, 12, 12, 12], ...
    'ColumnSpacing', 3);
helpers.createGridSplitter(grid, 1, 2, 'column', 1, 3);

statusPanel = uipanel(grid, 'Title', 'Prepared Plan');
statusPanel.Layout.Row = 1;
statusPanel.Layout.Column = 1;
statusGrid = uigridlayout(statusPanel, [6, 2], ...
    'ColumnWidth', {130, '1x'}, ...
    'RowHeight', {'fit', 'fit', 'fit', 'fit', 'fit', '1x'}, ...
    'Padding', [18, 18, 18, 18], ...
    'RowSpacing', 12);
helpers.enableScrolling(statusGrid);
helpers.createRightLabel(statusGrid, 'Plan Type', 1, 1);
runUi.RunPlanTypeField = uieditfield(statusGrid, 'text', 'Editable', 'off');
runUi.RunPlanTypeField.Layout.Row = 1; runUi.RunPlanTypeField.Layout.Column = 2;
helpers.createRightLabel(statusGrid, 'Source', 2, 1);
runUi.RunSourceField = uieditfield(statusGrid, 'text', 'Editable', 'off');
runUi.RunSourceField.Layout.Row = 2; runUi.RunSourceField.Layout.Column = 2;
helpers.createRightLabel(statusGrid, 'Readiness', 3, 1);
runUi.RunSupportedField = uieditfield(statusGrid, 'text', 'Editable', 'off');
runUi.RunSupportedField.Layout.Row = 3; runUi.RunSupportedField.Layout.Column = 2;
helpers.createRightLabel(statusGrid, 'Progress', 4, 1);
runUi.RunProgressField = uieditfield(statusGrid, 'text', 'Editable', 'off');
runUi.RunProgressField.Layout.Row = 4; runUi.RunProgressField.Layout.Column = 2;
helpers.createRightLabel(statusGrid, 'Current', 5, 1);
runUi.RunCurrentField = uieditfield(statusGrid, 'text', 'Editable', 'off');
runUi.RunCurrentField.Layout.Row = 5; runUi.RunCurrentField.Layout.Column = 2;
runUi.RunPlanHintLabel = uilabel(statusGrid, ...
    'Text', ['Execution type is derived from the prepared plan. ', ...
        'Edit and prepare Point, Path, or Z Sweep plans on the Plan tab.'], ...
    'WordWrap', 'on');
runUi.RunPlanHintLabel.Layout.Row = 6;
runUi.RunPlanHintLabel.Layout.Column = [1 2];

controlPanel = uipanel(grid, 'Title', 'Execution');
controlPanel.Layout.Row = 1;
controlPanel.Layout.Column = 3;
controlGrid = uigridlayout(controlPanel, [7, 1], ...
    'RowHeight', {'fit', 'fit', 'fit', 'fit', 'fit', 'fit', '1x'}, ...
    'Padding', [18, 18, 18, 18], ...
    'RowSpacing', 14);
helpers.enableScrolling(controlGrid);
runUi.AutoStandbyAfterRunCheckBox = uicheckbox(controlGrid, ...
    'Text', 'Auto standby after run');
runUi.AutoStandbyAfterRunCheckBox.Tooltip = ...
    'Send Carbide to standby after a run finishes normally';
runUi.GoToFirstPointButton = uibutton(controlGrid, 'Text', 'Go to First Point', ...
    'ButtonPushedFcn', callbacks.goToFirstPoint);
runUi.CheckBoundsButton = uibutton(controlGrid, 'Text', 'Check Bounds', ...
    'ButtonPushedFcn', callbacks.checkBounds);
runUi.StartRunButton = uibutton(controlGrid, 'Text', 'Run Plan', ...
    'BackgroundColor', [0.20, 0.70, 0.30], ...
    'FontColor', [1, 1, 1], ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', callbacks.startRun);
runUi.PauseResumeButton = uibutton(controlGrid, 'Text', 'Pause', ...
    'ButtonPushedFcn', callbacks.pauseResumeRun);
runUi.StopRunButton = uibutton(controlGrid, 'Text', 'STOP', ...
    'BackgroundColor', [0.95, 0.25, 0.25], ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', callbacks.stopRequested);
uilabel(controlGrid, ...
    'Text', 'Pause waits for a safe boundary; STOP requests a safe shutdown.', ...
    'WordWrap', 'on');
end
