function startGridResize(gridHandle, dimension, lowTrack, highTrack)
figHandle = uiFigureAncestor(gridHandle);
if isempty(figHandle) || ~isValidUiHandle(figHandle)
    return;
end

trackSizes = gridTrackSizes(gridHandle, dimension);
lowWeight = trackFlexValue(trackSizes{lowTrack});
highWeight = trackFlexValue(trackSizes{highTrack});
if ~isfinite(lowWeight) || ~isfinite(highWeight)
    return;
end

resizeDrag = struct( ...
    'Grid', gridHandle, ...
    'Dimension', string(dimension), ...
    'LowTrack', lowTrack, ...
    'HighTrack', highTrack, ...
    'StartPoint', figHandle.CurrentPoint, ...
    'StartSizes', {trackSizes}, ...
    'StartLowWeight', lowWeight, ...
    'StartHighWeight', highWeight, ...
    'MinPixels', 90, ...
    'PreviousMotionFcn', figHandle.WindowButtonMotionFcn, ...
    'PreviousUpFcn', figHandle.WindowButtonUpFcn, ...
    'PreviousPointer', figHandle.Pointer);

setappdata(figHandle, 'LaserWritingGridResizeDrag', resizeDrag);
figHandle.WindowButtonMotionFcn = @onGridResizeDrag;
figHandle.WindowButtonUpFcn = @finishGridResize;
try
    figHandle.Pointer = 'fleur';
catch
end
end
