function targets = boundingBoxCornerTargets(analysis, yDisplayReference)
cornerDisplayMatrix = [ ...
    analysis.xRange(1), analysis.yDisplayRange(1), analysis.zRange(1); ...
    analysis.xRange(2), analysis.yDisplayRange(1), analysis.zRange(1); ...
    analysis.xRange(2), analysis.yDisplayRange(2), analysis.zRange(1); ...
    analysis.xRange(1), analysis.yDisplayRange(2), analysis.zRange(1); ...
    analysis.xRange(1), analysis.yDisplayRange(1), analysis.zRange(2); ...
    analysis.xRange(2), analysis.yDisplayRange(1), analysis.zRange(2); ...
    analysis.xRange(2), analysis.yDisplayRange(2), analysis.zRange(2); ...
    analysis.xRange(1), analysis.yDisplayRange(2), analysis.zRange(2)];

cornerStageMatrix = [ ...
    cornerDisplayMatrix(:, 1), ...
    yDisplayReference - cornerDisplayMatrix(:, 2), ...
    cornerDisplayMatrix(:, 3)];
cornerStageMatrix = unique(cornerStageMatrix, 'rows', 'stable');

targets = repmat(struct('x', 0, 'y', 0, 'z', 0), size(cornerStageMatrix, 1), 1);
for index = 1:size(cornerStageMatrix, 1)
    targets(index) = struct( ...
        'x', cornerStageMatrix(index, 1), ...
        'y', cornerStageMatrix(index, 2), ...
        'z', cornerStageMatrix(index, 3));
end
end
