function summaryText = lw_build_path_plan_preflight_summary_text( ...
        preflight, runMode, stagesConnected, daqConnected, carbideText, autoStandbyText)
%LW_BUILD_PATH_PLAN_PREFLIGHT_SUMMARY_TEXT Summarize canonical path runs.

analysis = preflight.analysis;
writingPlan = preflight.writingPlan;
if isfield(preflight, 'pathGroups')
    pathGroups = preflight.pathGroups;
else
    pathGroups = lw_path_plan_groups(writingPlan);
end

segmentLengths = sqrt((writingPlan.x2 - writingPlan.x) .^ 2 + ...
    (writingPlan.y2 - writingPlan.y) .^ 2 + ...
    (writingPlan.z2 - writingPlan.z) .^ 2);
groupLengths = arrayfun(@(group) localGroupLength(group.rows), pathGroups);
segmentCounts = arrayfun(@(group) group.rowCount, pathGroups);
laserOnMask = string(writingPlan.laserState) == "on";

summaryText = sprintf([ ...
    'Plan source: %s\n', ...
    'Run mode: %s\n', ...
    'Path Segments: %d (%d laser-on, %d laser-off)\n', ...
    'Path Groups: %d\n', ...
    'Segments per Group: %d to %d\n', ...
    'X range: %.3f to %.3f mm\n', ...
    'Y range: %.3f to %.3f mm\n', ...
    'Z range: %.3f to %.3f mm\n', ...
    'Execution Power: %.2f to %.2f %%\n', ...
    'Segment Speed: %.4g to %.4g mm/s\n', ...
    'Segment Length: %.4g to %.4g mm\n', ...
    'Group Length: %.4g to %.4g mm\n', ...
    'Pre-write settle at group start: %.6g to %.6g s\n', ...
    'Laser schedule: each path segment uses its explicit on/off state\n', ...
    'Hardware: Stage %s | DAQ %s\n', ...
    'Carbide: %s\n', ...
    'Auto Standby: %s'], ...
    char(planSource(preflight.trajectory)), char(runMode), ...
    height(writingPlan), nnz(laserOnMask), nnz(~laserOnMask), ...
    numel(pathGroups), min(segmentCounts), max(segmentCounts), ...
    analysis.xRange(1), analysis.xRange(2), ...
    analysis.yDisplayRange(1), analysis.yDisplayRange(2), ...
    analysis.zRange(1), analysis.zRange(2), ...
    analysis.powerRange(1), analysis.powerRange(2), ...
    min(writingPlan.speed), max(writingPlan.speed), ...
    min(segmentLengths), max(segmentLengths), ...
    min(groupLengths), max(groupLengths), ...
    min(writingPlan.pauseSeconds), max(writingPlan.pauseSeconds), ...
    connectionText(stagesConnected), connectionText(daqConnected), ...
    char(carbideText), char(autoStandbyText));
end

function lengthMm = localGroupLength(rows)
lengthMm = sum(sqrt((rows.x2 - rows.x) .^ 2 + ...
    (rows.y2 - rows.y) .^ 2 + (rows.z2 - rows.z) .^ 2));
end

function sourceText = planSource(traj)
sourceText = "Unknown";
if isfield(traj, 'sourceType')
    sourceText = string(traj.sourceType);
end
end

function textValue = connectionText(isConnected)
if isConnected
    textValue = 'Connected';
else
    textValue = 'Disconnected';
end
end
