function summaryText = lw_build_z_sweep_preflight_summary_text(preflight, stagesConnected, daqConnected, carbideText, autoStandbyText)
sweep = preflight.sweep;
summaryText = sprintf([ ...
    'Run mode: Z Sweep Mode\n', ...
    'X: %.3f mm\n', ...
    'Y: %.3f mm\n', ...
    'Z Back: %.3f mm\n', ...
    'Z Front: %.3f mm\n', ...
    'Repeat Count: %d\n', ...
    'Exposure Direction: %s\n', ...
    'Sweep Speed: %.3f mm/s\n', ...
    'Return Speed: %.3f mm/s\n', ...
    'Z Acceleration: %.0f mm/s^2\n', ...
    'Sweep Accel Distance: %s\n', ...
    'Return Accel Distance: %s\n', ...
    'Sweep Power: %.2f %%\n', ...
    'Exposed Sweeps: %d\n', ...
    'Hardware: Stage %s | DAQ %s\n', ...
    'Carbide: %s\n', ...
    'Auto Standby: %s'], ...
    sweep.x, sweep.displayY, sweep.zBack, sweep.zFront, ...
    sweep.repeatCount, char(sweep.exposureDirection), ...
    sweep.sweepSpeedMmPerSecond, sweep.returnSpeedMmPerSecond, ...
    sweep.zAcceleration, ...
    char(formatAccelerationDistance(sweep.sweepSpeedMmPerSecond, sweep.zAcceleration)), ...
    char(formatAccelerationDistance(sweep.returnSpeedMmPerSecond, sweep.zAcceleration)), ...
    sweep.powerPercent, preflight.exposedSweepCount, ...
    connectionText(stagesConnected), connectionText(daqConnected), ...
    char(carbideText), char(autoStandbyText));
end

function textValue = formatAccelerationDistance(speedMmPerSecond, accelerationMmPerSecondSquared)
if accelerationMmPerSecondSquared <= 0
    textValue = "Using stage default acceleration";
    return;
end

distanceMm = speedMmPerSecond ^ 2 / (2 * accelerationMmPerSecondSquared);
textValue = sprintf('%.6f mm (%.3f um)', distanceMm, distanceMm * 1000);
end

function textValue = connectionText(isConnected)
if isConnected
    textValue = 'Connected';
else
    textValue = 'Disconnected';
end
end
