function summaryText = lw_build_cut_plan_preflight_summary_text(preflight, runMode, stagesConnected, daqConnected, carbideText, autoStandbyText)
%LW_BUILD_CUT_PLAN_PREFLIGHT_SUMMARY_TEXT Summarize continuous cut-plan runs.

analysis = preflight.analysis;
cutPlan = preflight.cutPlan;
if isfield(preflight, 'cutGroups')
    cutGroups = preflight.cutGroups;
else
    cutGroups = lw_cut_plan_groups(cutPlan);
end

cutLengths = sqrt((cutPlan.x2 - cutPlan.x) .^ 2 + ...
    (cutPlan.y2 - cutPlan.y) .^ 2 + ...
    (cutPlan.z2 - cutPlan.z) .^ 2);
[groupLeadLengths, groupExitLengths, groupCutLengths, segmentCounts] = localGroupMetrics(cutGroups);

summaryText = sprintf([ ...
    'Plan source: %s\n', ...
    'Run mode: %s\n', ...
    'Cut Rows: %d\n', ...
    'Cut Groups: %d\n', ...
    'Segments per Group: %d to %d\n', ...
    'X range: %.3f to %.3f mm\n', ...
    'Y range: %.3f to %.3f mm\n', ...
    'Z range: %.3f to %.3f mm\n', ...
    'Execution Power: %.2f to %.2f %%\n', ...
    'Cut Speed: %.4g to %.4g mm/s\n', ...
    'Lead Speed: %.4g to %.4g mm/s\n', ...
    'Cut Segment Length: %.4g to %.4g mm\n', ...
    'Cut Group Length: %.4g to %.4g mm\n', ...
    'Lead-in: %.4g to %.4g mm | Lead-out: %.4g to %.4g mm\n', ...
    'Pre-write settle at lead-in: %.6g to %.6g s\n', ...
    'Laser schedule: OFF during group lead-in/out, ON continuously within each cut group\n', ...
    'Hardware: Stage %s | DAQ %s\n', ...
    'Carbide: %s\n', ...
    'Auto Standby: %s'], ...
    char(planSource(preflight.trajectory)), char(runMode), height(cutPlan), numel(cutGroups), ...
    min(segmentCounts), max(segmentCounts), ...
    analysis.xRange(1), analysis.xRange(2), ...
    analysis.yDisplayRange(1), analysis.yDisplayRange(2), ...
    analysis.zRange(1), analysis.zRange(2), ...
    analysis.powerRange(1), analysis.powerRange(2), ...
    min(cutPlan.scanSpeed), max(cutPlan.scanSpeed), ...
    min(cutPlan.leadSpeed), max(cutPlan.leadSpeed), ...
    min(cutLengths), max(cutLengths), ...
    min(groupCutLengths), max(groupCutLengths), ...
    min(groupLeadLengths), max(groupLeadLengths), min(groupExitLengths), max(groupExitLengths), ...
    min(cutPlan.pauseSeconds), max(cutPlan.pauseSeconds), ...
    connectionText(stagesConnected), connectionText(daqConnected), ...
    char(carbideText), char(autoStandbyText));
end

function [leadLengths, exitLengths, cutLengths, segmentCounts] = localGroupMetrics(cutGroups)
groupCount = numel(cutGroups);
leadLengths = zeros(groupCount, 1);
exitLengths = zeros(groupCount, 1);
cutLengths = zeros(groupCount, 1);
segmentCounts = zeros(groupCount, 1);

for iGroup = 1:groupCount
    rows = cutGroups(iGroup).rows;
    firstRow = rows(1, :);
    lastRow = rows(end, :);
    leadLengths(iGroup) = sqrt((firstRow.x - firstRow.leadX) .^ 2 + ...
        (firstRow.y - firstRow.leadY) .^ 2 + ...
        (firstRow.z - firstRow.leadZ) .^ 2);
    exitLengths(iGroup) = sqrt((lastRow.exitX - lastRow.x2) .^ 2 + ...
        (lastRow.exitY - lastRow.y2) .^ 2 + ...
        (lastRow.exitZ - lastRow.z2) .^ 2);
    segmentLengths = sqrt((rows.x2 - rows.x) .^ 2 + ...
        (rows.y2 - rows.y) .^ 2 + ...
        (rows.z2 - rows.z) .^ 2);
    cutLengths(iGroup) = sum(segmentLengths);
    segmentCounts(iGroup) = height(rows);
end
end

function sourceText = planSource(traj)
sourceText = "Unknown";
if isfield(traj, 'sourceType')
    sourceText = string(traj.sourceType);
end
end

function textValue = connectionText(isConnected)
if isConnected
    textValue = 'Connected';
else
    textValue = 'Disconnected';
end
end
