function summaryText = lw_build_bounds_summary_text(analysis)
if analysis.inBounds
    outOfBoundsText = 'No';
else
    outOfBoundsText = 'Yes';
end

summaryText = sprintf([ ...
    'Points: %d\n', ...
    'X range: %.3f to %.3f mm\n', ...
    'Y range: %.3f to %.3f mm\n', ...
    'Z range: %.3f to %.3f mm\n', ...
    'Bounding box: %.3f x %.3f x %.3f mm\n', ...
    'Out of bounds: %s'], ...
    analysis.pointCount, ...
    analysis.xRange(1), analysis.xRange(2), ...
    analysis.yDisplayRange(1), analysis.yDisplayRange(2), ...
    analysis.zRange(1), analysis.zRange(2), ...
    analysis.boundingBoxSize(1), analysis.boundingBoxSize(2), analysis.boundingBoxSize(3), ...
    outOfBoundsText);
end
