function summaryText = lw_build_z_sweep_matrix_preflight_summary_text(preflight, stagesConnected, daqConnected, carbideText, autoStandbyText)
sweep = preflight.sweep;
matrix = preflight.matrix;
fastestSweepSpeed = max(arrayfun(@(run) run.sweep.sweepSpeedMmPerSecond, matrix.runs));
summaryText = sprintf([ ...
    'Run mode: Z Sweep Matrix\n', ...
    'Grid: %d rows x %d columns (%d runs)\n', ...
    'Blocks: %s\n', ...
    'Columns / X: %s = %s\n', ...
    'Rows / Y: %s = %s\n', ...
    'Start X: %.3f mm | X range: %.3f to %.3f mm\n', ...
    'Start Y: %.3f mm | Y range: %.3f to %.3f mm\n', ...
    'Pitch X: %.3f mm | Pitch Y: %.3f mm\n', ...
    'Z Back: %.3f mm | Z Front: %.3f mm\n', ...
    'Base Power: %.2f %% | Base Sweep Speed: %.3f mm/s\n', ...
    'Base Return Speed: %.3f mm/s | Base Repeat Count: %d\n', ...
    'Base Exposure Direction: %s\n', ...
    'Z Acceleration: %.0f mm/s^2\n', ...
    'Max Sweep Accel Distance: %s\n', ...
    'Exposed Sweeps: %d\n', ...
    'Hardware: Stage %s | DAQ %s\n', ...
    'Carbide: %s\n', ...
    'Auto Standby: %s'], ...
    matrix.rows, matrix.columns, matrix.runCount, ...
    char(formatZSweepBlockSummary(matrix)), ...
    char(matrix.xParameter), char(formatZSweepMatrixValueList(matrix.xParameter, matrix.xValues)), ...
    char(matrix.yParameter), char(formatZSweepMatrixValueList(matrix.yParameter, matrix.yValues)), ...
    sweep.x, matrix.xRange(1), matrix.xRange(2), ...
    sweep.displayY, matrix.displayYRange(1), matrix.displayYRange(2), ...
    matrix.pitchX, matrix.pitchY, ...
    sweep.zBack, sweep.zFront, ...
    sweep.powerPercent, sweep.sweepSpeedMmPerSecond, ...
    sweep.returnSpeedMmPerSecond, sweep.repeatCount, ...
    char(sweep.exposureDirection), ...
    sweep.zAcceleration, ...
    char(formatAccelerationDistance(fastestSweepSpeed, sweep.zAcceleration)), ...
    preflight.exposedSweepCount, ...
    connectionText(stagesConnected), connectionText(daqConnected), ...
    char(carbideText), char(autoStandbyText));
end

function textValue = formatZSweepBlockSummary(matrix)
blockConfig = matrix.block;
if ~blockConfig.enabled
    textValue = "Off";
    return;
end

textParts = strings(1, numel(blockConfig.parameters));
for parameterIndex = 1:numel(blockConfig.parameters)
    parameterName = blockConfig.parameters(parameterIndex);
    textParts(parameterIndex) = sprintf('%s = %s', ...
        char(parameterName), ...
        char(formatZSweepMatrixValueList(parameterName, blockConfig.values{parameterIndex})));
end

textValue = sprintf('%d blocks (%d columns x %d rows), %s, block pitch %.3f x %.3f mm', ...
    blockConfig.count, blockConfig.columns, blockConfig.rows, ...
    char(strjoin(textParts, ' | ')), blockConfig.pitchX, blockConfig.pitchY);
end

function textValue = formatZSweepMatrixValueList(parameterName, values)
if string(parameterName) == "Exposure Direction"
    textParts = cellstr(values(:).');
else
    textParts = arrayfun(@formatCompactNumber, double(values(:).'), 'UniformOutput', false);
end
textValue = strjoin(textParts, ', ');
end

function textValue = formatCompactNumber(value)
if abs(value - round(value)) < 1e-9
    textValue = sprintf('%.0f', value);
else
    textValue = sprintf('%.3f', value);
end
end

function textValue = formatAccelerationDistance(speedMmPerSecond, accelerationMmPerSecondSquared)
if accelerationMmPerSecondSquared <= 0
    textValue = "Using stage default acceleration";
    return;
end

distanceMm = speedMmPerSecond ^ 2 / (2 * accelerationMmPerSecondSquared);
textValue = sprintf('%.6f mm (%.3f um)', distanceMm, distanceMm * 1000);
end

function textValue = connectionText(isConnected)
if isConnected
    textValue = 'Connected';
else
    textValue = 'Disconnected';
end
end
