function summaryText = lw_build_pulse_run_preflight_summary_text(preflight, runMode, stagesConnected, daqConnected, carbideText, autoStandbyText)
analysis = preflight.analysis;
summaryText = sprintf([ ...
    'Plan source: %s\n', ...
    'Run mode: %s\n', ...
    'Points: %d\n', ...
    'X range: %.3f to %.3f mm\n', ...
    'Y range: %.3f to %.3f mm\n', ...
    'Z range: %.3f to %.3f mm\n', ...
    'Stream Speed: %.3f mm/s\n', ...
    'Execution Power: %.2f %%\n', ...
    'TTL Gate Width: %.3f us\n', ...
    'Inverse gate period: %.3f kHz (reference only)\n', ...
    'Pulse semantics: level-gated burst; optical pulse count is not synchronized\n', ...
    'Hardware: Stage %s | DAQ %s\n', ...
    'Carbide: %s\n', ...
    'Auto Standby: %s'], ...
    char(planSource(preflight.trajectory)), char(runMode), analysis.pointCount, ...
    analysis.xRange(1), analysis.xRange(2), ...
    analysis.yDisplayRange(1), analysis.yDisplayRange(2), ...
    analysis.zRange(1), analysis.zRange(2), ...
    preflight.pulseSpeedMmPerSecond, preflight.powerPercent, ...
    preflight.ttlGateWidthUs, preflight.inverseGatePeriodKHz, ...
    connectionText(stagesConnected), connectionText(daqConnected), ...
    char(carbideText), char(autoStandbyText));
end

function sourceText = planSource(traj)
sourceText = "Unknown";
if isfield(traj, 'sourceType')
    sourceText = string(traj.sourceType);
end
end

function textValue = connectionText(isConnected)
if isConnected
    textValue = 'Connected';
else
    textValue = 'Disconnected';
end
end
