function summaryText = lw_build_run_preflight_summary_text(preflight, runMode, stagesConnected, daqConnected, carbideText, autoStandbyText)
analysis = preflight.analysis;
timing = preflight.pointTiming;
summaryText = sprintf([ ...
    'Plan source: %s\n', ...
    'Run mode: %s\n', ...
    'Points: %d\n', ...
    'X range: %.3f to %.3f mm\n', ...
    'Y range: %.3f to %.3f mm\n', ...
    'Z range: %.3f to %.3f mm\n', ...
    'Execution Power: %s\n', ...
    'Timing source: %s\n', ...
    'Point dwell: %.3f to %.3f us (Zaber hardware schedule)\n', ...
    'Pre-write settle: %.6g to %.6g s\n', ...
    'Zero-dwell points: %d\n', ...
    'Zaber schedule: minimum %.3f us | resolution %.3f us\n', ...
    'Hardware: Stage %s | DAQ %s\n', ...
    'Carbide: %s\n', ...
    'Auto Standby: %s'], ...
    char(planSource(preflight.trajectory)), char(runMode), analysis.pointCount, ...
    analysis.xRange(1), analysis.xRange(2), ...
    analysis.yDisplayRange(1), analysis.yDisplayRange(2), ...
    analysis.zRange(1), analysis.zRange(2), ...
    char(preflightPowerSummaryText(preflight.trajectory, analysis)), ...
    char(pointTimingSourceText(timing.source)), ...
    timing.dwellMicrosecondsMin, timing.dwellMicrosecondsMax, ...
    timing.preWritePauseSecondsMin, timing.preWritePauseSecondsMax, ...
    timing.zeroDwellPointCount, timing.hardwareScheduleMinimumUs, ...
    timing.hardwareScheduleResolutionUs, ...
    connectionText(stagesConnected), connectionText(daqConnected), ...
    char(carbideText), char(autoStandbyText));
end

function textValue = pointTimingSourceText(source)
switch string(source)
    case "writing_plan"
        textValue = 'writing-plan dwell_s and pause_s';
    case "ui_defaults"
        textValue = 'Run-tab fallback dwell and settle';
    otherwise
        textValue = char(string(source));
end
end

function textValue = preflightPowerSummaryText(traj, analysis)
if any(~isfinite(analysis.powerRange))
    textValue = "Unavailable";
    return;
end

sourceText = powerSourceText(traj);
if abs(diff(analysis.powerRange)) <= 1e-9
    textValue = sprintf('%.2f %% (%s)', analysis.powerRange(1), sourceText);
else
    textValue = sprintf('%.2f to %.2f %% (%s)', analysis.powerRange(1), analysis.powerRange(2), sourceText);
end
end

function textValue = powerSourceText(traj)
if trajectoryPowerSource(traj) == "file"
    textValue = 'file';
else
    textValue = 'Plan input';
end
end

function sourceText = planSource(traj)
sourceText = "Unknown";
if isfield(traj, 'sourceType')
    sourceText = string(traj.sourceType);
end
end

function textValue = connectionText(isConnected)
if isConnected
    textValue = 'Connected';
else
    textValue = 'Disconnected';
end
end
