function summaryText = lw_build_3d_imaging_preflight_summary_text(preflight, stagesConnected, flirConnected)
summaryText = sprintf([ ...
    'Mode: FLIR 3D Imaging\n', ...
    'Frames: %d\n', ...
    'X: %.3f mm\n', ...
    'Y: %.3f mm\n', ...
    'Z: %.3f to %.3f mm\n', ...
    'Z Step: %.3f mm\n', ...
    'Settling Time: %.3f s\n', ...
    'FLIR Exposure: %.6g us\n', ...
    'Auto Exposure: %s\n', ...
    'FLIR Gain: %.6g dB\n', ...
    'Capture Timeout: %d ms\n', ...
    'Output Folder: %s\n', ...
    'TIFF Stack: %s\n', ...
    'SLM: %s\n', ...
    'Hardware: Stage %s | FLIR %s'], ...
    numel(preflight.zPositions), ...
    preflight.x, preflight.displayY, preflight.zStart, preflight.zEnd, ...
    preflight.zStep, preflight.settlingTime, preflight.exposureUs, ...
    char(formatAutoExposurePreflightSummary(preflight)), ...
    preflight.gain, preflight.captureTimeoutMs, preflight.runFolder, preflight.stackFile, ...
    char(formatSlmPreflightSummary(preflight.slmSnapshot, preflight.slmFilenameToken)), ...
    connectionText(stagesConnected), connectionText(flirConnected));
end

function textValue = formatAutoExposurePreflightSummary(preflight)
textValue = "Off";
if ~isfield(preflight, 'autoExposure') || ~isstruct(preflight.autoExposure) || ...
        ~isfield(preflight.autoExposure, 'enabled') || ~logical(preflight.autoExposure.enabled)
    return;
end

sampleCount = 0;
if isfield(preflight.autoExposure, 'sampleCount')
    sampleCount = preflight.autoExposure.sampleCount;
end
safetyFactor = 0.8;
if isfield(preflight.autoExposure, 'safetyFactor')
    safetyFactor = preflight.autoExposure.safetyFactor;
end
safetyPercent = 100 * safetyFactor;
textValue = sprintf('On (%d Z samples, %.0f%% no-clip target)', sampleCount, safetyPercent);
end

function textValue = formatSlmPreflightSummary(snapshot, filenameToken)
textValue = "No current SLM Bessel parameters";
if ~isstruct(snapshot) || ~isfield(snapshot, 'options') || ~isstruct(snapshot.options)
    return;
end

updatedAt = "-";
currentOnSlm = "-";
if isfield(snapshot, 'updatedAt')
    updatedAt = string(snapshot.updatedAt);
end
if isfield(snapshot, 'currentOnSlm')
    currentOnSlm = string(snapshot.currentOnSlm);
end
textValue = sprintf('Using current Bessel params (%s), current on SLM: %s, updated %s', ...
    char(filenameToken), char(currentOnSlm), char(updatedAt));
end

function textValue = connectionText(isConnected)
if isConnected
    textValue = 'Connected';
else
    textValue = 'Disconnected';
end
end
