function summaryText = lw_build_run_preflight_summary_text(preflight, runMode, stagesConnected, daqConnected, carbideText, autoStandbyText)
analysis = preflight.analysis;
summaryText = sprintf([ ...
    'Plan source: %s\n', ...
    'Run mode: %s\n', ...
    'Points: %d\n', ...
    'X range: %.3f to %.3f mm\n', ...
    'Y range: %.3f to %.3f mm\n', ...
    'Z range: %.3f to %.3f mm\n', ...
    'Execution Power: %s\n', ...
    'Point Exp: %.3f us\n', ...
    'Point Pause: %.3f s\n', ...
    'Hardware: Stage %s | DAQ %s\n', ...
    'Carbide: %s\n', ...
    'Auto Standby: %s'], ...
    char(planSource(preflight.trajectory)), char(runMode), analysis.pointCount, ...
    analysis.xRange(1), analysis.xRange(2), ...
    analysis.yDisplayRange(1), analysis.yDisplayRange(2), ...
    analysis.zRange(1), analysis.zRange(2), ...
    char(preflightPowerSummaryText(preflight.trajectory, analysis)), ...
    preflight.exposureMicroseconds, preflight.pauseSeconds, ...
    connectionText(stagesConnected), connectionText(daqConnected), ...
    char(carbideText), char(autoStandbyText));
end

function textValue = preflightPowerSummaryText(traj, analysis)
if any(~isfinite(analysis.powerRange))
    textValue = "Unavailable";
    return;
end

sourceText = powerSourceText(traj);
if abs(diff(analysis.powerRange)) <= 1e-9
    textValue = sprintf('%.2f %% (%s)', analysis.powerRange(1), sourceText);
else
    textValue = sprintf('%.2f to %.2f %% (%s)', analysis.powerRange(1), analysis.powerRange(2), sourceText);
end
end

function textValue = powerSourceText(traj)
if trajectoryPowerSource(traj) == "file"
    textValue = 'file';
else
    textValue = 'Plan input';
end
end

function sourceText = planSource(traj)
sourceText = "Unknown";
if isfield(traj, 'sourceType')
    sourceText = string(traj.sourceType);
end
end

function textValue = connectionText(isConnected)
if isConnected
    textValue = 'Connected';
else
    textValue = 'Disconnected';
end
end
