function pulseEnergyUj = carbidePulseEnergyMicroJoules(source)
pulseEnergyUj = carbideNumericField(source, [ ...
    "ActualOutputEnergy", ...
    "ActualPulseEnergyUj", ...
    "ActualPulseEnergyMicroJ", ...
    "PulseEnergyUj", ...
    "PulseEnergyMicroJ", ...
    "EnergyPerPulseUj", ...
    "EnergyPerPulseMicroJ"]);
if isfinite(pulseEnergyUj)
    return;
end

actualPowerW = carbideNumericField(source, ["ActualOutputPower", "OutputPower", "ActualPower"]);
actualFrequencyKHz = carbideNumericField(source, ["ActualOutputFrequency", "ActualFrequency", "OutputFrequency"]);
if isfinite(actualPowerW) && isfinite(actualFrequencyKHz) && actualFrequencyKHz > 0
    pulseEnergyUj = actualPowerW / actualFrequencyKHz * 1000;
end
end
