function textValue = formatCarbideSnapshot(snapshot)
if ~isfield(snapshot, 'connected') || ~logical(snapshot.connected)
    textValue = "Disconnected";
    if isfield(snapshot, 'lastError') && strlength(string(snapshot.lastError)) > 0
        textValue = sprintf('Disconnected (%s)', compactErrorMessage(snapshot.lastError));
    end
    return;
end

presetText = "-";
if isfield(snapshot, 'selectedPreset') && strlength(string(snapshot.selectedPreset)) > 0
    presetText = char(snapshot.selectedPreset);
end

textValue = sprintf('Preset %s | output %s | shutter %s | PP %s/%s | pulse %s/%s | E %s uJ | power %s | freq %s', ...
    presetText, ...
    formatSnapshotLogical(snapshot.isOutputEnabled), ...
    char(snapshot.shutterState), ...
    formatSnapshotNumber(snapshot.actualPpDivider), ...
    formatSnapshotNumber(snapshot.targetPpDivider), ...
    formatSnapshotNumber(snapshot.actualPulseDuration), ...
    formatSnapshotNumber(snapshot.targetPulseDuration), ...
    formatSnapshotNumber(snapshot.pulseEnergyUj), ...
    formatSnapshotNumber(snapshot.actualPower), ...
    formatSnapshotNumber(snapshot.actualFrequency));
end
