function plan = lw_manual_exposure_stream_plan(exposureTimeSeconds, repeatCount, intervalSeconds, config)
%LW_MANUAL_EXPOSURE_STREAM_PLAN Validate and quantize a manual stream sequence.

exposureUs = lw_validate_stage_schedule_duration_us( ...
    positiveScalar(exposureTimeSeconds, 'Exposure duration') .* 1e6, ...
    config, 'Manual exposure duration', false);
repeatCount = positiveInteger(repeatCount, 'Repeat count');
intervalSeconds = nonnegativeScalar(intervalSeconds, 'Interval');

waitResolutionUs = localPositiveIntegerConfig( ...
    config, 'streamWaitResolutionUs', 1000, 'Stream wait resolution');
if mod(waitResolutionUs, 1000) ~= 0
    error('lw:stage:InvalidStreamWaitResolution', ...
        'Stream wait resolution must be a whole number of milliseconds.');
end

intervalUsRaw = intervalSeconds .* 1e6;
intervalUs = round(intervalUsRaw);
if abs(intervalUsRaw - intervalUs) > 1e-6
    error('lw:stage:StreamIntervalResolution', ...
        ['Interval %.12g s is not representable as a whole number of microseconds. ', ...
        'Change the requested value instead of relying on implicit rounding.'], ...
        intervalSeconds);
end

cycleUs = exposureUs + intervalUs;
cycleWaitMilliseconds = [];
if repeatCount > 1
    if cycleUs < waitResolutionUs
        error('lw:stage:StreamCycleBelowMinimum', ...
            ['For Repeat greater than 1, Exposure + Interval must be at least %.9g ms. ', ...
            'The requested cycle is %.9g ms.'], ...
            waitResolutionUs .* 1e-3, cycleUs .* 1e-3);
    end
    if mod(cycleUs, waitResolutionUs) ~= 0
        error('lw:stage:StreamCycleResolution', ...
            ['For Repeat greater than 1, Exposure + Interval must be an exact multiple ', ...
            'of %.9g ms for the Zaber stream. The requested cycle is %.9g ms. ', ...
            'Change Interval; no timing value was rounded.'], ...
            waitResolutionUs .* 1e-3, cycleUs .* 1e-3);
    end
    cycleWaitMilliseconds = cycleUs .* 1e-3;
end

finalWaitMilliseconds = max(1, ceil(exposureUs ./ 1000));
maximumStreamWaitMilliseconds = 4294967295;
if (~isempty(cycleWaitMilliseconds) && ...
        cycleWaitMilliseconds > maximumStreamWaitMilliseconds) || ...
        finalWaitMilliseconds > maximumStreamWaitMilliseconds
    error('lw:stage:StreamWaitTooLong', ...
        'The requested Manual Exposure wait exceeds the Zaber stream limit.');
end

plan = struct( ...
    'exposureUs', exposureUs, ...
    'exposureSeconds', exposureUs .* 1e-6, ...
    'repeatCount', repeatCount, ...
    'intervalUs', intervalUs, ...
    'intervalSeconds', intervalUs .* 1e-6, ...
    'cycleUs', cycleUs, ...
    'cycleWaitMilliseconds', cycleWaitMilliseconds, ...
    'finalWaitMilliseconds', finalWaitMilliseconds, ...
    'expectedOpticalDurationSeconds', ...
        repeatCount .* exposureUs .* 1e-6 + ...
        (repeatCount - 1) .* intervalUs .* 1e-6, ...
    'expectedStreamBusySeconds', ...
        (repeatCount - 1) .* cycleUs .* 1e-6 + ...
        finalWaitMilliseconds .* 1e-3);
end

function value = localPositiveIntegerConfig(config, fieldName, fallbackValue, label)
value = fallbackValue;
if isstruct(config) && isfield(config, 'stage') && isstruct(config.stage) && ...
        isfield(config.stage, fieldName)
    value = config.stage.(fieldName);
end
value = positiveInteger(value, label);
end
