function rows = lw_empty_imaging_auto_exposure_scout_rows()
%LW_EMPTY_IMAGING_AUTO_EXPOSURE_SCOUT_ROWS Empty auto-exposure scout table rows.

rows = struct( ...
    'Attempt', {}, ...
    'SampleIndex', {}, ...
    'ActualSampleCount', {}, ...
    'X_mm', {}, ...
    'Y_display_mm', {}, ...
    'Y_stage_mm', {}, ...
    'Z_mm', {}, ...
    'Exposure_us', {}, ...
    'MaxIntensity', {}, ...
    'FullScale', {}, ...
    'SaturatedPixels', {}, ...
    'SaturatedFraction', {}, ...
    'PixelCount', {}, ...
    'PixelFormat', {}, ...
    'CameraFrameID', {}, ...
    'CameraTimestamp', {}, ...
    'Timestamp', {});
end
