function rows = lw_empty_imaging_metadata_rows()
%LW_EMPTY_IMAGING_METADATA_ROWS Empty metadata row template for 3D imaging.

rows = struct( ...
    'Index', {}, ...
    'X_mm', {}, ...
    'Y_display_mm', {}, ...
    'Y_stage_mm', {}, ...
    'Z_mm', {}, ...
    'Filename', {}, ...
    'TiffPage', {}, ...
    'Timestamp', {}, ...
    'CameraFrameID', {}, ...
    'CameraTimestamp', {}, ...
    'PixelFormat', {}, ...
    'Exposure_us', {}, ...
    'Gain_dB', {}, ...
    'CarbidePulseEnergy_uJ', {}, ...
    'SLMUpdatedAt', {}, ...
    'SLMCurrentOnSlm', {}, ...
    'SLMCurrentPattern', {}, ...
    'SLMCurrentAdjustedPattern', {}, ...
    'SLMAxiconMode', {}, ...
    'SLMAxiconConeAngle_deg', {}, ...
    'SLMAxiconRadialPeriod_mm', {}, ...
    'SLMAxiconRadialPeriod_px', {}, ...
    'SLMAxiconRadialCycles', {}, ...
    'SLMAxiconIndex', {}, ...
    'SLMAxiconPhysicalBaseAngle_deg', {}, ...
    'SLMVortexCharge', {}, ...
    'SLMHelicalGamma', {}, ...
    'SLMHelicalOrder', {}, ...
    'SLMHelicalOffset_deg', {}, ...
    'SLMOmegaInner', {}, ...
    'SLMOmegaOuter', {}, ...
    'SLMGlobalLensFocal_mm', {}, ...
    'SLMGlobalXShift_2pi', {}, ...
    'SLMGlobalYShift_2pi', {}, ...
    'SLMGlobalApertureRadius_px', {}, ...
    'SLMGlobalApertureCenterX_px', {}, ...
    'SLMGlobalApertureCenterY_px', {}, ...
    'CaptureRegion', {}, ...
    'OffsetX', {}, ...
    'OffsetY', {}, ...
    'SensorWidth', {}, ...
    'SensorHeight', {}, ...
    'Width', {}, ...
    'Height', {});
end
