function row = lw_imaging_auto_exposure_scout_row(attempt, sampleIndex, ...
    actualSampleCount, target, yDisplay, exposureUs, stats, info)
%LW_IMAGING_AUTO_EXPOSURE_SCOUT_ROW Build one auto-exposure scout row.

capturedAt = "";
if isfield(info, 'CapturedAt')
    capturedAt = string(info.CapturedAt);
end

frameId = uint64(0);
if isfield(info, 'FrameID')
    frameId = uint64(info.FrameID);
end

cameraTimestamp = uint64(0);
if isfield(info, 'Timestamp')
    cameraTimestamp = uint64(info.Timestamp);
end

pixelFormat = "";
if isfield(info, 'PixelFormat')
    pixelFormat = string(info.PixelFormat);
end

row = struct( ...
    'Attempt', attempt, ...
    'SampleIndex', sampleIndex, ...
    'ActualSampleCount', actualSampleCount, ...
    'X_mm', target.x, ...
    'Y_display_mm', yDisplay, ...
    'Y_stage_mm', target.y, ...
    'Z_mm', target.z, ...
    'Exposure_us', exposureUs, ...
    'MaxIntensity', stats.maxIntensity, ...
    'FullScale', stats.fullScale, ...
    'SaturatedPixels', stats.saturatedPixels, ...
    'SaturatedFraction', stats.saturatedFraction, ...
    'PixelCount', stats.pixelCount, ...
    'PixelFormat', pixelFormat, ...
    'CameraFrameID', frameId, ...
    'CameraTimestamp', cameraTimestamp, ...
    'Timestamp', capturedAt);
end
