function row = lw_imaging_metadata_row(index, target, yDisplay, fileName, ...
    tiffPage, info, exposureUs, gainDb, carbidePulseEnergyUj, slmSnapshot)
%LW_IMAGING_METADATA_ROW Build one metadata row for a captured 3D image.

capturedAt = "";
if isfield(info, 'CapturedAt')
    capturedAt = string(info.CapturedAt);
end

captureRegion = flirInfoRegionName(info);
offsetX = 0;
offsetY = 0;
sensorWidth = info.Width;
sensorHeight = info.Height;
if isfield(info, 'OffsetX')
    offsetX = info.OffsetX;
end
if isfield(info, 'OffsetY')
    offsetY = info.OffsetY;
end
if isfield(info, 'SensorWidth')
    sensorWidth = info.SensorWidth;
end
if isfield(info, 'SensorHeight')
    sensorHeight = info.SensorHeight;
end

slmRow = slmMetadataFields(slmSnapshot);
row = struct( ...
    'Index', index, ...
    'X_mm', target.x, ...
    'Y_display_mm', yDisplay, ...
    'Y_stage_mm', target.y, ...
    'Z_mm', target.z, ...
    'Filename', string(fileName), ...
    'TiffPage', tiffPage, ...
    'Timestamp', capturedAt, ...
    'CameraFrameID', uint64(info.FrameID), ...
    'CameraTimestamp', uint64(info.Timestamp), ...
    'PixelFormat', string(info.PixelFormat), ...
    'Exposure_us', exposureUs, ...
    'Gain_dB', gainDb, ...
    'CarbidePulseEnergy_uJ', carbidePulseEnergyUj, ...
    'SLMUpdatedAt', slmRow.UpdatedAt, ...
    'SLMCurrentOnSlm', slmRow.CurrentOnSlm, ...
    'SLMCurrentPattern', slmRow.CurrentPattern, ...
    'SLMCurrentAdjustedPattern', slmRow.CurrentAdjustedPattern, ...
    'SLMAxiconMode', slmRow.AxiconMode, ...
    'SLMAxiconConeAngle_deg', slmRow.AxiconConeAngleDeg, ...
    'SLMAxiconRadialPeriod_mm', slmRow.AxiconRadialPeriodMm, ...
    'SLMAxiconRadialPeriod_px', slmRow.AxiconRadialPeriodPx, ...
    'SLMAxiconRadialCycles', slmRow.AxiconRadialCycles, ...
    'SLMAxiconIndex', slmRow.AxiconIndex, ...
    'SLMAxiconPhysicalBaseAngle_deg', slmRow.AxiconPhysicalBaseAngleDeg, ...
    'SLMVortexCharge', slmRow.VortexCharge, ...
    'SLMHelicalGamma', slmRow.HelicalGamma, ...
    'SLMHelicalOrder', slmRow.HelicalOrder, ...
    'SLMHelicalOffset_deg', slmRow.HelicalOffsetDeg, ...
    'SLMOmegaInner', slmRow.OmegaInner, ...
    'SLMOmegaOuter', slmRow.OmegaOuter, ...
    'SLMGlobalLensFocal_mm', slmRow.GlobalLensFocalMm, ...
    'SLMGlobalXShift_2pi', slmRow.GlobalXShiftTwoPi, ...
    'SLMGlobalYShift_2pi', slmRow.GlobalYShiftTwoPi, ...
    'SLMGlobalApertureRadius_px', slmRow.GlobalApertureRadiusPx, ...
    'SLMGlobalApertureCenterX_px', slmRow.GlobalApertureCenterXpx, ...
    'SLMGlobalApertureCenterY_px', slmRow.GlobalApertureCenterYpx, ...
    'CaptureRegion', captureRegion, ...
    'OffsetX', offsetX, ...
    'OffsetY', offsetY, ...
    'SensorWidth', sensorWidth, ...
    'SensorHeight', sensorHeight, ...
    'Width', info.Width, ...
    'Height', info.Height);
end

function regionName = flirInfoRegionName(info)
regionName = "";
if isstruct(info) && isfield(info, 'RegionName') && ~isempty(info.RegionName)
    regionName = string(info.RegionName);
elseif isstruct(info) && isfield(info, 'Name') && ~isempty(info.Name)
    regionName = string(info.Name);
end
end

function fields = slmMetadataFields(snapshot)
options = struct();
globalAdjustments = struct();
if isstruct(snapshot)
    if isfield(snapshot, 'options') && isstruct(snapshot.options)
        options = snapshot.options;
    end
    if isfield(snapshot, 'globalAdjustments') && isstruct(snapshot.globalAdjustments)
        globalAdjustments = snapshot.globalAdjustments;
    end
end

fields = struct( ...
    'UpdatedAt', slmSnapshotString(snapshot, 'updatedAt'), ...
    'CurrentOnSlm', slmSnapshotString(snapshot, 'currentOnSlm'), ...
    'CurrentPattern', slmSnapshotString(snapshot, 'currentPatternName'), ...
    'CurrentAdjustedPattern', slmSnapshotString(snapshot, 'currentAdjustedPatternName'), ...
    'AxiconMode', slmOptionString(options, 'axiconMode'), ...
    'AxiconConeAngleDeg', slmOptionValue(options, 'axiconConeAngleDeg'), ...
    'AxiconRadialPeriodMm', slmOptionValue(options, 'axiconRadialPeriodMm'), ...
    'AxiconRadialPeriodPx', slmOptionValue(options, 'axiconRadialPeriodPx'), ...
    'AxiconRadialCycles', slmOptionValue(options, 'axiconRadialCycles'), ...
    'AxiconIndex', slmOptionValue(options, 'axiconIndex'), ...
    'AxiconPhysicalBaseAngleDeg', slmOptionValue(options, 'axiconPhysicalBaseAngleDeg'), ...
    'VortexCharge', slmOptionValue(options, 'vortexCharge'), ...
    'HelicalGamma', slmOptionValue(options, 'helicalGamma'), ...
    'HelicalOrder', slmOptionValue(options, 'helicalOrder'), ...
    'HelicalOffsetDeg', slmOptionValue(options, 'helicalOffsetDeg'), ...
    'OmegaInner', slmOptionValue(options, 'omegaInner'), ...
    'OmegaOuter', slmOptionValue(options, 'omegaOuter'), ...
    'GlobalLensFocalMm', slmOptionValue(globalAdjustments, 'lensFocalLengthMm'), ...
    'GlobalXShiftTwoPi', slmOptionValue(globalAdjustments, 'xShiftTwoPi'), ...
    'GlobalYShiftTwoPi', slmOptionValue(globalAdjustments, 'yShiftTwoPi'), ...
    'GlobalApertureRadiusPx', slmOptionValue(globalAdjustments, 'apertureRadiusPx'), ...
    'GlobalApertureCenterXpx', slmOptionValue(globalAdjustments, 'apertureCenterXpx'), ...
    'GlobalApertureCenterYpx', slmOptionValue(globalAdjustments, 'apertureCenterYpx'));
end

function value = slmSnapshotString(snapshot, fieldName)
value = "";
if isstruct(snapshot) && isfield(snapshot, fieldName)
    try
        value = string(snapshot.(fieldName));
    catch
        value = "";
    end
end
end

function value = slmOptionString(options, fieldName)
value = "";
if isstruct(options) && isfield(options, fieldName)
    try
        value = string(options.(fieldName));
    catch
        value = "";
    end
end
end

function value = slmOptionValue(options, fieldName)
value = NaN;
if isstruct(options) && isfield(options, fieldName)
    try
        value = double(options.(fieldName));
    catch
        value = NaN;
    end
end
if ~isscalar(value)
    value = NaN;
end
end
